%% -*- Mode: LaTeX Memoir; tab-width: 4;

%% DLUTThesis.cls    DLUT PhD Thesis
%%
%% Created by Dazhi Jiang, 2011-01-05 17:09:33 +0000 (Wed,  5 Jan 2011)
%% Copyright (c) 2016 Dazhi Jiang All Rights Reserved.

%% TextMate Settings
%!TEX TS-program = pdflatex
%!TEX TS-options = -shell-escape -interaction=nonstopmode -file-line-error

% \includeonly{SUACSEThesis-A-frontmatter,SUACSEThesis-D-NDT}
% \includeonly{SUACSEThesis-A-frontmatter,SUACSEThesis-E-ICA}

\pdfminorversion=5 % to allow compression
\pdfobjcompresslevel=2

%% !!!
% \RequirePackage{etex} % This needs an additional output stream
% \documentclass[10pt,a4paper,extrafontsizes,oldfontcommands,oneside]{memoir}
\documentclass[11pt,a4paper,extrafontsizes,oldfontcommands,oneside]{memoir}
% \documentclass[11pt,a4paper,extrafontsizes,oldfontcommands,oneside,draft]{memoir}
% \listfiles

\usepackage{morewrites}
